- id: sync-python-matrix
  name: Sync GitHub Actions Python version matrix
  description: Update matrix entries in GitHub Actions workflow files based on the Python versions specified in pyproject.toml classifiers.
  entry: python main.py
  language: python
  pass_filenames: true
  files: ^pyproject\.toml$|^\.github/workflows/.*\.ya?ml$
